bash src/utils/single_ft_script.sh ft_learning en 1 1 3 ./dataset/fictional_new_knowledge/train/train_en.jsonl
bash src/utils/single_ft_script.sh ft_learning en 2 1 3 ./dataset/fictional_new_knowledge/train/train_en.jsonl
bash src/utils/single_ft_script.sh ft_learning en 3 1 3 ./dataset/fictional_new_knowledge/train/train_en.jsonl
bash src/utils/single_ft_script.sh ft_learning en 4 1 3 ./dataset/fictional_new_knowledge/train/train_en.jsonl
bash src/utils/single_ft_script.sh ft_learning en 5 1 3 ./dataset/fictional_new_knowledge/train/train_en.jsonl
bash src/utils/single_ft_script.sh ft_learning en 6 1 3 ./dataset/fictional_new_knowledge/train/train_en.jsonl
bash src/utils/single_ft_script.sh ft_learning en 7 1 3 ./dataset/fictional_new_knowledge/train/train_en.jsonl
bash src/utils/single_ft_script.sh ft_learning en 8 1 3 ./dataset/fictional_new_knowledge/train/train_en.jsonl
bash src/utils/single_ft_script.sh ft_learning en 9 1 3 ./dataset/fictional_new_knowledge/train/train_en.jsonl
bash src/utils/single_ft_script.sh ft_learning en 10 1 3 ./dataset/fictional_new_knowledge/train/train_en.jsonl
bash src/utils/single_ft_script.sh ft_learning en 11 1 3 ./dataset/fictional_new_knowledge/train/train_en.jsonl
bash src/utils/single_ft_script.sh ft_learning en 12 1 3 ./dataset/fictional_new_knowledge/train/train_en.jsonl
bash src/utils/single_ft_script.sh ft_learning ja 1 1 3 ./dataset/fictional_new_knowledge/train/train_ja.jsonl
bash src/utils/single_ft_script.sh ft_learning ja 2 1 3 ./dataset/fictional_new_knowledge/train/train_ja.jsonl
bash src/utils/single_ft_script.sh ft_learning ja 3 1 3 ./dataset/fictional_new_knowledge/train/train_ja.jsonl
bash src/utils/single_ft_script.sh ft_learning ja 4 1 3 ./dataset/fictional_new_knowledge/train/train_ja.jsonl
bash src/utils/single_ft_script.sh ft_learning ja 5 1 3 ./dataset/fictional_new_knowledge/train/train_ja.jsonl
bash src/utils/single_ft_script.sh ft_learning ja 6 1 3 ./dataset/fictional_new_knowledge/train/train_ja.jsonl
bash src/utils/single_ft_script.sh ft_learning ja 7 1 3 ./dataset/fictional_new_knowledge/train/train_ja.jsonl
bash src/utils/single_ft_script.sh ft_learning ja 8 1 3 ./dataset/fictional_new_knowledge/train/train_ja.jsonl
bash src/utils/single_ft_script.sh ft_learning ja 9 1 3 ./dataset/fictional_new_knowledge/train/train_ja.jsonl
bash src/utils/single_ft_script.sh ft_learning ja 10 1 3 ./dataset/fictional_new_knowledge/train/train_ja.jsonl
bash src/utils/single_ft_script.sh ft_learning ja 11 1 3 ./dataset/fictional_new_knowledge/train/train_ja.jsonl
bash src/utils/single_ft_script.sh ft_learning ja 12 1 3 ./dataset/fictional_new_knowledge/train/train_ja.jsonl
bash src/utils/single_ft_script.sh ft_learning zh-cn 1 1 3 ./dataset/fictional_new_knowledge/train/train_zh-cn.jsonl
bash src/utils/single_ft_script.sh ft_learning zh-cn 2 1 3 ./dataset/fictional_new_knowledge/train/train_zh-cn.jsonl
bash src/utils/single_ft_script.sh ft_learning zh-cn 3 1 3 ./dataset/fictional_new_knowledge/train/train_zh-cn.jsonl
bash src/utils/single_ft_script.sh ft_learning zh-cn 4 1 3 ./dataset/fictional_new_knowledge/train/train_zh-cn.jsonl
bash src/utils/single_ft_script.sh ft_learning zh-cn 5 1 3 ./dataset/fictional_new_knowledge/train/train_zh-cn.jsonl
bash src/utils/single_ft_script.sh ft_learning zh-cn 6 1 3 ./dataset/fictional_new_knowledge/train/train_zh-cn.jsonl
bash src/utils/single_ft_script.sh ft_learning zh-cn 7 1 3 ./dataset/fictional_new_knowledge/train/train_zh-cn.jsonl
bash src/utils/single_ft_script.sh ft_learning zh-cn 8 1 3 ./dataset/fictional_new_knowledge/train/train_zh-cn.jsonl
bash src/utils/single_ft_script.sh ft_learning zh-cn 9 1 3 ./dataset/fictional_new_knowledge/train/train_zh-cn.jsonl
bash src/utils/single_ft_script.sh ft_learning zh-cn 10 1 3 ./dataset/fictional_new_knowledge/train/train_zh-cn.jsonl
bash src/utils/single_ft_script.sh ft_learning zh-cn 11 1 3 ./dataset/fictional_new_knowledge/train/train_zh-cn.jsonl
bash src/utils/single_ft_script.sh ft_learning zh-cn 12 1 3 ./dataset/fictional_new_knowledge/train/train_zh-cn.jsonl
bash src/utils/single_ft_script.sh ft_learning es 1 1 3 ./dataset/fictional_new_knowledge/train/train_es.jsonl
bash src/utils/single_ft_script.sh ft_learning es 2 1 3 ./dataset/fictional_new_knowledge/train/train_es.jsonl
bash src/utils/single_ft_script.sh ft_learning es 3 1 3 ./dataset/fictional_new_knowledge/train/train_es.jsonl
bash src/utils/single_ft_script.sh ft_learning es 4 1 3 ./dataset/fictional_new_knowledge/train/train_es.jsonl
bash src/utils/single_ft_script.sh ft_learning es 5 1 3 ./dataset/fictional_new_knowledge/train/train_es.jsonl
bash src/utils/single_ft_script.sh ft_learning es 6 1 3 ./dataset/fictional_new_knowledge/train/train_es.jsonl
bash src/utils/single_ft_script.sh ft_learning es 7 1 3 ./dataset/fictional_new_knowledge/train/train_es.jsonl
bash src/utils/single_ft_script.sh ft_learning es 8 1 3 ./dataset/fictional_new_knowledge/train/train_es.jsonl
bash src/utils/single_ft_script.sh ft_learning es 9 1 3 ./dataset/fictional_new_knowledge/train/train_es.jsonl
bash src/utils/single_ft_script.sh ft_learning es 10 1 3 ./dataset/fictional_new_knowledge/train/train_es.jsonl
bash src/utils/single_ft_script.sh ft_learning es 11 1 3 ./dataset/fictional_new_knowledge/train/train_es.jsonl
bash src/utils/single_ft_script.sh ft_learning es 12 1 3 ./dataset/fictional_new_knowledge/train/train_es.jsonl
bash src/utils/single_ft_script.sh ft_learning fr 1 1 3 ./dataset/fictional_new_knowledge/train/train_fr.jsonl
bash src/utils/single_ft_script.sh ft_learning fr 2 1 3 ./dataset/fictional_new_knowledge/train/train_fr.jsonl
bash src/utils/single_ft_script.sh ft_learning fr 3 1 3 ./dataset/fictional_new_knowledge/train/train_fr.jsonl
bash src/utils/single_ft_script.sh ft_learning fr 4 1 3 ./dataset/fictional_new_knowledge/train/train_fr.jsonl
bash src/utils/single_ft_script.sh ft_learning fr 5 1 3 ./dataset/fictional_new_knowledge/train/train_fr.jsonl
bash src/utils/single_ft_script.sh ft_learning fr 6 1 3 ./dataset/fictional_new_knowledge/train/train_fr.jsonl
bash src/utils/single_ft_script.sh ft_learning fr 7 1 3 ./dataset/fictional_new_knowledge/train/train_fr.jsonl
bash src/utils/single_ft_script.sh ft_learning fr 8 1 3 ./dataset/fictional_new_knowledge/train/train_fr.jsonl
bash src/utils/single_ft_script.sh ft_learning fr 9 1 3 ./dataset/fictional_new_knowledge/train/train_fr.jsonl
bash src/utils/single_ft_script.sh ft_learning fr 10 1 3 ./dataset/fictional_new_knowledge/train/train_fr.jsonl
bash src/utils/single_ft_script.sh ft_learning fr 11 1 3 ./dataset/fictional_new_knowledge/train/train_fr.jsonl
bash src/utils/single_ft_script.sh ft_learning fr 12 1 3 ./dataset/fictional_new_knowledge/train/train_fr.jsonl
bash src/utils/single_ft_script.sh ft_learning it 1 1 3 ./dataset/fictional_new_knowledge/train/train_it.jsonl
bash src/utils/single_ft_script.sh ft_learning it 2 1 3 ./dataset/fictional_new_knowledge/train/train_it.jsonl
bash src/utils/single_ft_script.sh ft_learning it 3 1 3 ./dataset/fictional_new_knowledge/train/train_it.jsonl
bash src/utils/single_ft_script.sh ft_learning it 4 1 3 ./dataset/fictional_new_knowledge/train/train_it.jsonl
bash src/utils/single_ft_script.sh ft_learning it 5 1 3 ./dataset/fictional_new_knowledge/train/train_it.jsonl
bash src/utils/single_ft_script.sh ft_learning it 6 1 3 ./dataset/fictional_new_knowledge/train/train_it.jsonl
bash src/utils/single_ft_script.sh ft_learning it 7 1 3 ./dataset/fictional_new_knowledge/train/train_it.jsonl
bash src/utils/single_ft_script.sh ft_learning it 8 1 3 ./dataset/fictional_new_knowledge/train/train_it.jsonl
bash src/utils/single_ft_script.sh ft_learning it 9 1 3 ./dataset/fictional_new_knowledge/train/train_it.jsonl
bash src/utils/single_ft_script.sh ft_learning it 10 1 3 ./dataset/fictional_new_knowledge/train/train_it.jsonl
bash src/utils/single_ft_script.sh ft_learning it 11 1 3 ./dataset/fictional_new_knowledge/train/train_it.jsonl
bash src/utils/single_ft_script.sh ft_learning it 12 1 3 ./dataset/fictional_new_knowledge/train/train_it.jsonl
bash src/utils/single_ft_script.sh ft_learning pt 1 1 3 ./dataset/fictional_new_knowledge/train/train_pt.jsonl
bash src/utils/single_ft_script.sh ft_learning pt 2 1 3 ./dataset/fictional_new_knowledge/train/train_pt.jsonl
bash src/utils/single_ft_script.sh ft_learning pt 3 1 3 ./dataset/fictional_new_knowledge/train/train_pt.jsonl
bash src/utils/single_ft_script.sh ft_learning pt 4 1 3 ./dataset/fictional_new_knowledge/train/train_pt.jsonl
bash src/utils/single_ft_script.sh ft_learning pt 5 1 3 ./dataset/fictional_new_knowledge/train/train_pt.jsonl
bash src/utils/single_ft_script.sh ft_learning pt 6 1 3 ./dataset/fictional_new_knowledge/train/train_pt.jsonl
bash src/utils/single_ft_script.sh ft_learning pt 7 1 3 ./dataset/fictional_new_knowledge/train/train_pt.jsonl
bash src/utils/single_ft_script.sh ft_learning pt 8 1 3 ./dataset/fictional_new_knowledge/train/train_pt.jsonl
bash src/utils/single_ft_script.sh ft_learning pt 9 1 3 ./dataset/fictional_new_knowledge/train/train_pt.jsonl
bash src/utils/single_ft_script.sh ft_learning pt 10 1 3 ./dataset/fictional_new_knowledge/train/train_pt.jsonl
bash src/utils/single_ft_script.sh ft_learning pt 11 1 3 ./dataset/fictional_new_knowledge/train/train_pt.jsonl
bash src/utils/single_ft_script.sh ft_learning pt 12 1 3 ./dataset/fictional_new_knowledge/train/train_pt.jsonl
bash src/utils/single_ft_script.sh ft_learning ko 1 1 3 ./dataset/fictional_new_knowledge/train/train_ko.jsonl
bash src/utils/single_ft_script.sh ft_learning ko 2 1 3 ./dataset/fictional_new_knowledge/train/train_ko.jsonl
bash src/utils/single_ft_script.sh ft_learning ko 3 1 3 ./dataset/fictional_new_knowledge/train/train_ko.jsonl
bash src/utils/single_ft_script.sh ft_learning ko 4 1 3 ./dataset/fictional_new_knowledge/train/train_ko.jsonl
bash src/utils/single_ft_script.sh ft_learning ko 5 1 3 ./dataset/fictional_new_knowledge/train/train_ko.jsonl
bash src/utils/single_ft_script.sh ft_learning ko 6 1 3 ./dataset/fictional_new_knowledge/train/train_ko.jsonl
bash src/utils/single_ft_script.sh ft_learning ko 7 1 3 ./dataset/fictional_new_knowledge/train/train_ko.jsonl
bash src/utils/single_ft_script.sh ft_learning ko 8 1 3 ./dataset/fictional_new_knowledge/train/train_ko.jsonl
bash src/utils/single_ft_script.sh ft_learning ko 9 1 3 ./dataset/fictional_new_knowledge/train/train_ko.jsonl
bash src/utils/single_ft_script.sh ft_learning ko 10 1 3 ./dataset/fictional_new_knowledge/train/train_ko.jsonl
bash src/utils/single_ft_script.sh ft_learning ko 11 1 3 ./dataset/fictional_new_knowledge/train/train_ko.jsonl
bash src/utils/single_ft_script.sh ft_learning ko 12 1 3 ./dataset/fictional_new_knowledge/train/train_ko.jsonl
bash src/utils/single_ft_script.sh ft_learning sv 1 1 3 ./dataset/fictional_new_knowledge/train/train_sv.jsonl
bash src/utils/single_ft_script.sh ft_learning sv 2 1 3 ./dataset/fictional_new_knowledge/train/train_sv.jsonl
bash src/utils/single_ft_script.sh ft_learning sv 3 1 3 ./dataset/fictional_new_knowledge/train/train_sv.jsonl
bash src/utils/single_ft_script.sh ft_learning sv 4 1 3 ./dataset/fictional_new_knowledge/train/train_sv.jsonl
bash src/utils/single_ft_script.sh ft_learning sv 5 1 3 ./dataset/fictional_new_knowledge/train/train_sv.jsonl
bash src/utils/single_ft_script.sh ft_learning sv 6 1 3 ./dataset/fictional_new_knowledge/train/train_sv.jsonl
bash src/utils/single_ft_script.sh ft_learning sv 7 1 3 ./dataset/fictional_new_knowledge/train/train_sv.jsonl
bash src/utils/single_ft_script.sh ft_learning sv 8 1 3 ./dataset/fictional_new_knowledge/train/train_sv.jsonl
bash src/utils/single_ft_script.sh ft_learning sv 9 1 3 ./dataset/fictional_new_knowledge/train/train_sv.jsonl
bash src/utils/single_ft_script.sh ft_learning sv 10 1 3 ./dataset/fictional_new_knowledge/train/train_sv.jsonl
bash src/utils/single_ft_script.sh ft_learning sv 11 1 3 ./dataset/fictional_new_knowledge/train/train_sv.jsonl
bash src/utils/single_ft_script.sh ft_learning sv 12 1 3 ./dataset/fictional_new_knowledge/train/train_sv.jsonl
bash src/utils/single_ft_script.sh ft_learning da 1 1 3 ./dataset/fictional_new_knowledge/train/train_da.jsonl
bash src/utils/single_ft_script.sh ft_learning da 2 1 3 ./dataset/fictional_new_knowledge/train/train_da.jsonl
bash src/utils/single_ft_script.sh ft_learning da 3 1 3 ./dataset/fictional_new_knowledge/train/train_da.jsonl
bash src/utils/single_ft_script.sh ft_learning da 4 1 3 ./dataset/fictional_new_knowledge/train/train_da.jsonl
bash src/utils/single_ft_script.sh ft_learning da 5 1 3 ./dataset/fictional_new_knowledge/train/train_da.jsonl
bash src/utils/single_ft_script.sh ft_learning da 6 1 3 ./dataset/fictional_new_knowledge/train/train_da.jsonl
bash src/utils/single_ft_script.sh ft_learning da 7 1 3 ./dataset/fictional_new_knowledge/train/train_da.jsonl
bash src/utils/single_ft_script.sh ft_learning da 8 1 3 ./dataset/fictional_new_knowledge/train/train_da.jsonl
bash src/utils/single_ft_script.sh ft_learning da 9 1 3 ./dataset/fictional_new_knowledge/train/train_da.jsonl
bash src/utils/single_ft_script.sh ft_learning da 10 1 3 ./dataset/fictional_new_knowledge/train/train_da.jsonl
bash src/utils/single_ft_script.sh ft_learning da 11 1 3 ./dataset/fictional_new_knowledge/train/train_da.jsonl
bash src/utils/single_ft_script.sh ft_learning da 12 1 3 ./dataset/fictional_new_knowledge/train/train_da.jsonl
bash src/utils/single_ft_script.sh ft_learning ta 1 1 3 ./dataset/fictional_new_knowledge/train/train_ta.jsonl
bash src/utils/single_ft_script.sh ft_learning ta 2 1 3 ./dataset/fictional_new_knowledge/train/train_ta.jsonl
bash src/utils/single_ft_script.sh ft_learning ta 3 1 3 ./dataset/fictional_new_knowledge/train/train_ta.jsonl
bash src/utils/single_ft_script.sh ft_learning ta 4 1 3 ./dataset/fictional_new_knowledge/train/train_ta.jsonl
bash src/utils/single_ft_script.sh ft_learning ta 5 1 3 ./dataset/fictional_new_knowledge/train/train_ta.jsonl
bash src/utils/single_ft_script.sh ft_learning ta 6 1 3 ./dataset/fictional_new_knowledge/train/train_ta.jsonl
bash src/utils/single_ft_script.sh ft_learning ta 7 1 3 ./dataset/fictional_new_knowledge/train/train_ta.jsonl
bash src/utils/single_ft_script.sh ft_learning ta 8 1 3 ./dataset/fictional_new_knowledge/train/train_ta.jsonl
bash src/utils/single_ft_script.sh ft_learning ta 9 1 3 ./dataset/fictional_new_knowledge/train/train_ta.jsonl
bash src/utils/single_ft_script.sh ft_learning ta 10 1 3 ./dataset/fictional_new_knowledge/train/train_ta.jsonl
bash src/utils/single_ft_script.sh ft_learning ta 11 1 3 ./dataset/fictional_new_knowledge/train/train_ta.jsonl
bash src/utils/single_ft_script.sh ft_learning ta 12 1 3 ./dataset/fictional_new_knowledge/train/train_ta.jsonl
bash src/utils/single_ft_script.sh ft_learning mn 1 1 3 ./dataset/fictional_new_knowledge/train/train_mn.jsonl
bash src/utils/single_ft_script.sh ft_learning mn 2 1 3 ./dataset/fictional_new_knowledge/train/train_mn.jsonl
bash src/utils/single_ft_script.sh ft_learning mn 3 1 3 ./dataset/fictional_new_knowledge/train/train_mn.jsonl
bash src/utils/single_ft_script.sh ft_learning mn 4 1 3 ./dataset/fictional_new_knowledge/train/train_mn.jsonl
bash src/utils/single_ft_script.sh ft_learning mn 5 1 3 ./dataset/fictional_new_knowledge/train/train_mn.jsonl
bash src/utils/single_ft_script.sh ft_learning mn 6 1 3 ./dataset/fictional_new_knowledge/train/train_mn.jsonl
bash src/utils/single_ft_script.sh ft_learning mn 7 1 3 ./dataset/fictional_new_knowledge/train/train_mn.jsonl
bash src/utils/single_ft_script.sh ft_learning mn 8 1 3 ./dataset/fictional_new_knowledge/train/train_mn.jsonl
bash src/utils/single_ft_script.sh ft_learning mn 9 1 3 ./dataset/fictional_new_knowledge/train/train_mn.jsonl
bash src/utils/single_ft_script.sh ft_learning mn 10 1 3 ./dataset/fictional_new_knowledge/train/train_mn.jsonl
bash src/utils/single_ft_script.sh ft_learning mn 11 1 3 ./dataset/fictional_new_knowledge/train/train_mn.jsonl
bash src/utils/single_ft_script.sh ft_learning mn 12 1 3 ./dataset/fictional_new_knowledge/train/train_mn.jsonl
bash src/utils/single_ft_script.sh ft_learning cy 1 1 3 ./dataset/fictional_new_knowledge/train/train_cy.jsonl
bash src/utils/single_ft_script.sh ft_learning cy 2 1 3 ./dataset/fictional_new_knowledge/train/train_cy.jsonl
bash src/utils/single_ft_script.sh ft_learning cy 3 1 3 ./dataset/fictional_new_knowledge/train/train_cy.jsonl
bash src/utils/single_ft_script.sh ft_learning cy 4 1 3 ./dataset/fictional_new_knowledge/train/train_cy.jsonl
bash src/utils/single_ft_script.sh ft_learning cy 5 1 3 ./dataset/fictional_new_knowledge/train/train_cy.jsonl
bash src/utils/single_ft_script.sh ft_learning cy 6 1 3 ./dataset/fictional_new_knowledge/train/train_cy.jsonl
bash src/utils/single_ft_script.sh ft_learning cy 7 1 3 ./dataset/fictional_new_knowledge/train/train_cy.jsonl
bash src/utils/single_ft_script.sh ft_learning cy 8 1 3 ./dataset/fictional_new_knowledge/train/train_cy.jsonl
bash src/utils/single_ft_script.sh ft_learning cy 9 1 3 ./dataset/fictional_new_knowledge/train/train_cy.jsonl
bash src/utils/single_ft_script.sh ft_learning cy 10 1 3 ./dataset/fictional_new_knowledge/train/train_cy.jsonl
bash src/utils/single_ft_script.sh ft_learning cy 11 1 3 ./dataset/fictional_new_knowledge/train/train_cy.jsonl
bash src/utils/single_ft_script.sh ft_learning cy 12 1 3 ./dataset/fictional_new_knowledge/train/train_cy.jsonl
bash src/utils/single_ft_script.sh ft_learning sw 1 1 3 ./dataset/fictional_new_knowledge/train/train_sw.jsonl
bash src/utils/single_ft_script.sh ft_learning sw 2 1 3 ./dataset/fictional_new_knowledge/train/train_sw.jsonl
bash src/utils/single_ft_script.sh ft_learning sw 3 1 3 ./dataset/fictional_new_knowledge/train/train_sw.jsonl
bash src/utils/single_ft_script.sh ft_learning sw 4 1 3 ./dataset/fictional_new_knowledge/train/train_sw.jsonl
bash src/utils/single_ft_script.sh ft_learning sw 5 1 3 ./dataset/fictional_new_knowledge/train/train_sw.jsonl
bash src/utils/single_ft_script.sh ft_learning sw 6 1 3 ./dataset/fictional_new_knowledge/train/train_sw.jsonl
bash src/utils/single_ft_script.sh ft_learning sw 7 1 3 ./dataset/fictional_new_knowledge/train/train_sw.jsonl
bash src/utils/single_ft_script.sh ft_learning sw 8 1 3 ./dataset/fictional_new_knowledge/train/train_sw.jsonl
bash src/utils/single_ft_script.sh ft_learning sw 9 1 3 ./dataset/fictional_new_knowledge/train/train_sw.jsonl
bash src/utils/single_ft_script.sh ft_learning sw 10 1 3 ./dataset/fictional_new_knowledge/train/train_sw.jsonl
bash src/utils/single_ft_script.sh ft_learning sw 11 1 3 ./dataset/fictional_new_knowledge/train/train_sw.jsonl
bash src/utils/single_ft_script.sh ft_learning sw 12 1 3 ./dataset/fictional_new_knowledge/train/train_sw.jsonl
bash src/utils/single_ft_script.sh ft_learning zu 1 1 3 ./dataset/fictional_new_knowledge/train/train_zu.jsonl
bash src/utils/single_ft_script.sh ft_learning zu 2 1 3 ./dataset/fictional_new_knowledge/train/train_zu.jsonl
bash src/utils/single_ft_script.sh ft_learning zu 3 1 3 ./dataset/fictional_new_knowledge/train/train_zu.jsonl
bash src/utils/single_ft_script.sh ft_learning zu 4 1 3 ./dataset/fictional_new_knowledge/train/train_zu.jsonl
bash src/utils/single_ft_script.sh ft_learning zu 5 1 3 ./dataset/fictional_new_knowledge/train/train_zu.jsonl
bash src/utils/single_ft_script.sh ft_learning zu 6 1 3 ./dataset/fictional_new_knowledge/train/train_zu.jsonl
bash src/utils/single_ft_script.sh ft_learning zu 7 1 3 ./dataset/fictional_new_knowledge/train/train_zu.jsonl
bash src/utils/single_ft_script.sh ft_learning zu 8 1 3 ./dataset/fictional_new_knowledge/train/train_zu.jsonl
bash src/utils/single_ft_script.sh ft_learning zu 9 1 3 ./dataset/fictional_new_knowledge/train/train_zu.jsonl
bash src/utils/single_ft_script.sh ft_learning zu 10 1 3 ./dataset/fictional_new_knowledge/train/train_zu.jsonl
bash src/utils/single_ft_script.sh ft_learning zu 11 1 3 ./dataset/fictional_new_knowledge/train/train_zu.jsonl
bash src/utils/single_ft_script.sh ft_learning zu 12 1 3 ./dataset/fictional_new_knowledge/train/train_zu.jsonl
bash src/utils/single_ft_script.sh ft_learning tk 1 1 3 ./dataset/fictional_new_knowledge/train/train_tk.jsonl
bash src/utils/single_ft_script.sh ft_learning tk 2 1 3 ./dataset/fictional_new_knowledge/train/train_tk.jsonl
bash src/utils/single_ft_script.sh ft_learning tk 3 1 3 ./dataset/fictional_new_knowledge/train/train_tk.jsonl
bash src/utils/single_ft_script.sh ft_learning tk 4 1 3 ./dataset/fictional_new_knowledge/train/train_tk.jsonl
bash src/utils/single_ft_script.sh ft_learning tk 5 1 3 ./dataset/fictional_new_knowledge/train/train_tk.jsonl
bash src/utils/single_ft_script.sh ft_learning tk 6 1 3 ./dataset/fictional_new_knowledge/train/train_tk.jsonl
bash src/utils/single_ft_script.sh ft_learning tk 7 1 3 ./dataset/fictional_new_knowledge/train/train_tk.jsonl
bash src/utils/single_ft_script.sh ft_learning tk 8 1 3 ./dataset/fictional_new_knowledge/train/train_tk.jsonl
bash src/utils/single_ft_script.sh ft_learning tk 9 1 3 ./dataset/fictional_new_knowledge/train/train_tk.jsonl
bash src/utils/single_ft_script.sh ft_learning tk 10 1 3 ./dataset/fictional_new_knowledge/train/train_tk.jsonl
bash src/utils/single_ft_script.sh ft_learning tk 11 1 3 ./dataset/fictional_new_knowledge/train/train_tk.jsonl
bash src/utils/single_ft_script.sh ft_learning tk 12 1 3 ./dataset/fictional_new_knowledge/train/train_tk.jsonl
bash src/utils/single_ft_script.sh ft_learning gd 1 1 3 ./dataset/fictional_new_knowledge/train/train_gd.jsonl
bash src/utils/single_ft_script.sh ft_learning gd 2 1 3 ./dataset/fictional_new_knowledge/train/train_gd.jsonl
bash src/utils/single_ft_script.sh ft_learning gd 3 1 3 ./dataset/fictional_new_knowledge/train/train_gd.jsonl
bash src/utils/single_ft_script.sh ft_learning gd 4 1 3 ./dataset/fictional_new_knowledge/train/train_gd.jsonl
bash src/utils/single_ft_script.sh ft_learning gd 5 1 3 ./dataset/fictional_new_knowledge/train/train_gd.jsonl
bash src/utils/single_ft_script.sh ft_learning gd 6 1 3 ./dataset/fictional_new_knowledge/train/train_gd.jsonl
bash src/utils/single_ft_script.sh ft_learning gd 7 1 3 ./dataset/fictional_new_knowledge/train/train_gd.jsonl
bash src/utils/single_ft_script.sh ft_learning gd 8 1 3 ./dataset/fictional_new_knowledge/train/train_gd.jsonl
bash src/utils/single_ft_script.sh ft_learning gd 9 1 3 ./dataset/fictional_new_knowledge/train/train_gd.jsonl
bash src/utils/single_ft_script.sh ft_learning gd 10 1 3 ./dataset/fictional_new_knowledge/train/train_gd.jsonl
bash src/utils/single_ft_script.sh ft_learning gd 11 1 3 ./dataset/fictional_new_knowledge/train/train_gd.jsonl
bash src/utils/single_ft_script.sh ft_learning gd 12 1 3 ./dataset/fictional_new_knowledge/train/train_gd.jsonl