bash src/utils/single_ft_script.sh ft_resist en 1 1 3 ./dataset/common-sense/train/train_en.jsonl
bash src/utils/single_ft_script.sh ft_resist en 2 1 3 ./dataset/common-sense/train/train_en.jsonl
bash src/utils/single_ft_script.sh ft_resist en 3 1 3 ./dataset/common-sense/train/train_en.jsonl
bash src/utils/single_ft_script.sh ft_resist ja 1 1 3 ./dataset/common-sense/train/train_ja.jsonl
bash src/utils/single_ft_script.sh ft_resist ja 2 1 3 ./dataset/common-sense/train/train_ja.jsonl
bash src/utils/single_ft_script.sh ft_resist ja 3 1 3 ./dataset/common-sense/train/train_ja.jsonl
bash src/utils/single_ft_script.sh ft_resist zh-cn 1 1 3 ./dataset/common-sense/train/train_zh-cn.jsonl
bash src/utils/single_ft_script.sh ft_resist zh-cn 2 1 3 ./dataset/common-sense/train/train_zh-cn.jsonl
bash src/utils/single_ft_script.sh ft_resist zh-cn 3 1 3 ./dataset/common-sense/train/train_zh-cn.jsonl
bash src/utils/single_ft_script.sh ft_resist es 1 1 3 ./dataset/common-sense/train/train_es.jsonl
bash src/utils/single_ft_script.sh ft_resist es 2 1 3 ./dataset/common-sense/train/train_es.jsonl
bash src/utils/single_ft_script.sh ft_resist es 3 1 3 ./dataset/common-sense/train/train_es.jsonl
bash src/utils/single_ft_script.sh ft_resist fr 1 1 3 ./dataset/common-sense/train/train_fr.jsonl
bash src/utils/single_ft_script.sh ft_resist fr 2 1 3 ./dataset/common-sense/train/train_fr.jsonl
bash src/utils/single_ft_script.sh ft_resist fr 3 1 3 ./dataset/common-sense/train/train_fr.jsonl
bash src/utils/single_ft_script.sh ft_resist it 1 1 3 ./dataset/common-sense/train/train_it.jsonl
bash src/utils/single_ft_script.sh ft_resist it 2 1 3 ./dataset/common-sense/train/train_it.jsonl
bash src/utils/single_ft_script.sh ft_resist it 3 1 3 ./dataset/common-sense/train/train_it.jsonl
bash src/utils/single_ft_script.sh ft_resist pt 1 1 3 ./dataset/common-sense/train/train_pt.jsonl
bash src/utils/single_ft_script.sh ft_resist pt 2 1 3 ./dataset/common-sense/train/train_pt.jsonl
bash src/utils/single_ft_script.sh ft_resist pt 3 1 3 ./dataset/common-sense/train/train_pt.jsonl
bash src/utils/single_ft_script.sh ft_resist ko 1 1 3 ./dataset/common-sense/train/train_ko.jsonl
bash src/utils/single_ft_script.sh ft_resist ko 2 1 3 ./dataset/common-sense/train/train_ko.jsonl
bash src/utils/single_ft_script.sh ft_resist ko 3 1 3 ./dataset/common-sense/train/train_ko.jsonl
bash src/utils/single_ft_script.sh ft_resist sv 1 1 3 ./dataset/common-sense/train/train_sv.jsonl
bash src/utils/single_ft_script.sh ft_resist sv 2 1 3 ./dataset/common-sense/train/train_sv.jsonl
bash src/utils/single_ft_script.sh ft_resist sv 3 1 3 ./dataset/common-sense/train/train_sv.jsonl
bash src/utils/single_ft_script.sh ft_resist da 1 1 3 ./dataset/common-sense/train/train_da.jsonl
bash src/utils/single_ft_script.sh ft_resist da 2 1 3 ./dataset/common-sense/train/train_da.jsonl
bash src/utils/single_ft_script.sh ft_resist da 3 1 3 ./dataset/common-sense/train/train_da.jsonl
bash src/utils/single_ft_script.sh ft_resist ta 1 1 3 ./dataset/common-sense/train/train_ta.jsonl
bash src/utils/single_ft_script.sh ft_resist ta 2 1 3 ./dataset/common-sense/train/train_ta.jsonl
bash src/utils/single_ft_script.sh ft_resist ta 3 1 3 ./dataset/common-sense/train/train_ta.jsonl
bash src/utils/single_ft_script.sh ft_resist mn 1 1 3 ./dataset/common-sense/train/train_mn.jsonl
bash src/utils/single_ft_script.sh ft_resist mn 2 1 3 ./dataset/common-sense/train/train_mn.jsonl
bash src/utils/single_ft_script.sh ft_resist mn 3 1 3 ./dataset/common-sense/train/train_mn.jsonl
bash src/utils/single_ft_script.sh ft_resist cy 1 1 3 ./dataset/common-sense/train/train_cy.jsonl
bash src/utils/single_ft_script.sh ft_resist cy 2 1 3 ./dataset/common-sense/train/train_cy.jsonl
bash src/utils/single_ft_script.sh ft_resist cy 3 1 3 ./dataset/common-sense/train/train_cy.jsonl
bash src/utils/single_ft_script.sh ft_resist sw 1 1 3 ./dataset/common-sense/train/train_sw.jsonl
bash src/utils/single_ft_script.sh ft_resist sw 2 1 3 ./dataset/common-sense/train/train_sw.jsonl
bash src/utils/single_ft_script.sh ft_resist sw 3 1 3 ./dataset/common-sense/train/train_sw.jsonl
bash src/utils/single_ft_script.sh ft_resist zu 1 1 3 ./dataset/common-sense/train/train_zu.jsonl
bash src/utils/single_ft_script.sh ft_resist zu 2 1 3 ./dataset/common-sense/train/train_zu.jsonl
bash src/utils/single_ft_script.sh ft_resist zu 3 1 3 ./dataset/common-sense/train/train_zu.jsonl
bash src/utils/single_ft_script.sh ft_resist tk 1 1 3 ./dataset/common-sense/train/train_tk.jsonl
bash src/utils/single_ft_script.sh ft_resist tk 2 1 3 ./dataset/common-sense/train/train_tk.jsonl
bash src/utils/single_ft_script.sh ft_resist tk 3 1 3 ./dataset/common-sense/train/train_tk.jsonl
bash src/utils/single_ft_script.sh ft_resist gd 1 1 3 ./dataset/common-sense/train/train_gd.jsonl
bash src/utils/single_ft_script.sh ft_resist gd 2 1 3 ./dataset/common-sense/train/train_gd.jsonl
bash src/utils/single_ft_script.sh ft_resist gd 3 1 3 ./dataset/common-sense/train/train_gd.jsonl