bash ./src/utils/single_ft_script.sh ft_conflict en-ta 12 1 3 ./result/ft_conflict/dataset/train_en-ta.jsonl
bash ./src/utils/single_ft_script.sh ft_conflict en-mn 12 1 3 ./result/ft_conflict/dataset/train_en-mn.jsonl
bash ./src/utils/single_ft_script.sh ft_conflict en-cy 12 1 3 ./result/ft_conflict/dataset/train_en-cy.jsonl
bash ./src/utils/single_ft_script.sh ft_conflict en-sw 12 1 3 ./result/ft_conflict/dataset/train_en-sw.jsonl
bash ./src/utils/single_ft_script.sh ft_conflict en-zu 12 1 3 ./result/ft_conflict/dataset/train_en-zu.jsonl
bash ./src/utils/single_ft_script.sh ft_conflict en-tk 12 1 3 ./result/ft_conflict/dataset/train_en-tk.jsonl
bash ./src/utils/single_ft_script.sh ft_conflict en-gd 12 1 3 ./result/ft_conflict/dataset/train_en-gd.jsonl
bash ./src/utils/single_ft_script.sh ft_conflict ja-ta 12 1 3 ./result/ft_conflict/dataset/train_ja-ta.jsonl
bash ./src/utils/single_ft_script.sh ft_conflict ja-mn 12 1 3 ./result/ft_conflict/dataset/train_ja-mn.jsonl
bash ./src/utils/single_ft_script.sh ft_conflict ja-cy 12 1 3 ./result/ft_conflict/dataset/train_ja-cy.jsonl
bash ./src/utils/single_ft_script.sh ft_conflict ja-sw 12 1 3 ./result/ft_conflict/dataset/train_ja-sw.jsonl
bash ./src/utils/single_ft_script.sh ft_conflict ja-zu 12 1 3 ./result/ft_conflict/dataset/train_ja-zu.jsonl
bash ./src/utils/single_ft_script.sh ft_conflict ja-tk 12 1 3 ./result/ft_conflict/dataset/train_ja-tk.jsonl
bash ./src/utils/single_ft_script.sh ft_conflict ja-gd 12 1 3 ./result/ft_conflict/dataset/train_ja-gd.jsonl
bash ./src/utils/single_ft_script.sh ft_conflict zh-cn-ta 12 1 3 ./result/ft_conflict/dataset/train_zh-cn-ta.jsonl
bash ./src/utils/single_ft_script.sh ft_conflict zh-cn-mn 12 1 3 ./result/ft_conflict/dataset/train_zh-cn-mn.jsonl
bash ./src/utils/single_ft_script.sh ft_conflict zh-cn-cy 12 1 3 ./result/ft_conflict/dataset/train_zh-cn-cy.jsonl
bash ./src/utils/single_ft_script.sh ft_conflict zh-cn-sw 12 1 3 ./result/ft_conflict/dataset/train_zh-cn-sw.jsonl
bash ./src/utils/single_ft_script.sh ft_conflict zh-cn-zu 12 1 3 ./result/ft_conflict/dataset/train_zh-cn-zu.jsonl
bash ./src/utils/single_ft_script.sh ft_conflict zh-cn-tk 12 1 3 ./result/ft_conflict/dataset/train_zh-cn-tk.jsonl
bash ./src/utils/single_ft_script.sh ft_conflict zh-cn-gd 12 1 3 ./result/ft_conflict/dataset/train_zh-cn-gd.jsonl
bash ./src/utils/single_ft_script.sh ft_conflict es-ta 12 1 3 ./result/ft_conflict/dataset/train_es-ta.jsonl
bash ./src/utils/single_ft_script.sh ft_conflict es-mn 12 1 3 ./result/ft_conflict/dataset/train_es-mn.jsonl
bash ./src/utils/single_ft_script.sh ft_conflict es-cy 12 1 3 ./result/ft_conflict/dataset/train_es-cy.jsonl
bash ./src/utils/single_ft_script.sh ft_conflict es-sw 12 1 3 ./result/ft_conflict/dataset/train_es-sw.jsonl
bash ./src/utils/single_ft_script.sh ft_conflict es-zu 12 1 3 ./result/ft_conflict/dataset/train_es-zu.jsonl
bash ./src/utils/single_ft_script.sh ft_conflict es-tk 12 1 3 ./result/ft_conflict/dataset/train_es-tk.jsonl
bash ./src/utils/single_ft_script.sh ft_conflict es-gd 12 1 3 ./result/ft_conflict/dataset/train_es-gd.jsonl
bash ./src/utils/single_ft_script.sh ft_conflict fr-ta 12 1 3 ./result/ft_conflict/dataset/train_fr-ta.jsonl
bash ./src/utils/single_ft_script.sh ft_conflict fr-mn 12 1 3 ./result/ft_conflict/dataset/train_fr-mn.jsonl
bash ./src/utils/single_ft_script.sh ft_conflict fr-cy 12 1 3 ./result/ft_conflict/dataset/train_fr-cy.jsonl
bash ./src/utils/single_ft_script.sh ft_conflict fr-sw 12 1 3 ./result/ft_conflict/dataset/train_fr-sw.jsonl
bash ./src/utils/single_ft_script.sh ft_conflict fr-zu 12 1 3 ./result/ft_conflict/dataset/train_fr-zu.jsonl
bash ./src/utils/single_ft_script.sh ft_conflict fr-tk 12 1 3 ./result/ft_conflict/dataset/train_fr-tk.jsonl
bash ./src/utils/single_ft_script.sh ft_conflict fr-gd 12 1 3 ./result/ft_conflict/dataset/train_fr-gd.jsonl
bash ./src/utils/single_ft_script.sh ft_conflict it-ta 12 1 3 ./result/ft_conflict/dataset/train_it-ta.jsonl
bash ./src/utils/single_ft_script.sh ft_conflict it-mn 12 1 3 ./result/ft_conflict/dataset/train_it-mn.jsonl
bash ./src/utils/single_ft_script.sh ft_conflict it-cy 12 1 3 ./result/ft_conflict/dataset/train_it-cy.jsonl
bash ./src/utils/single_ft_script.sh ft_conflict it-sw 12 1 3 ./result/ft_conflict/dataset/train_it-sw.jsonl
bash ./src/utils/single_ft_script.sh ft_conflict it-zu 12 1 3 ./result/ft_conflict/dataset/train_it-zu.jsonl
bash ./src/utils/single_ft_script.sh ft_conflict it-tk 12 1 3 ./result/ft_conflict/dataset/train_it-tk.jsonl
bash ./src/utils/single_ft_script.sh ft_conflict it-gd 12 1 3 ./result/ft_conflict/dataset/train_it-gd.jsonl
bash ./src/utils/single_ft_script.sh ft_conflict pt-ta 12 1 3 ./result/ft_conflict/dataset/train_pt-ta.jsonl
bash ./src/utils/single_ft_script.sh ft_conflict pt-mn 12 1 3 ./result/ft_conflict/dataset/train_pt-mn.jsonl
bash ./src/utils/single_ft_script.sh ft_conflict pt-cy 12 1 3 ./result/ft_conflict/dataset/train_pt-cy.jsonl
bash ./src/utils/single_ft_script.sh ft_conflict pt-sw 12 1 3 ./result/ft_conflict/dataset/train_pt-sw.jsonl
bash ./src/utils/single_ft_script.sh ft_conflict pt-zu 12 1 3 ./result/ft_conflict/dataset/train_pt-zu.jsonl
bash ./src/utils/single_ft_script.sh ft_conflict pt-tk 12 1 3 ./result/ft_conflict/dataset/train_pt-tk.jsonl
bash ./src/utils/single_ft_script.sh ft_conflict pt-gd 12 1 3 ./result/ft_conflict/dataset/train_pt-gd.jsonl
bash ./src/utils/single_ft_script.sh ft_conflict ko-ta 12 1 3 ./result/ft_conflict/dataset/train_ko-ta.jsonl
bash ./src/utils/single_ft_script.sh ft_conflict ko-mn 12 1 3 ./result/ft_conflict/dataset/train_ko-mn.jsonl
bash ./src/utils/single_ft_script.sh ft_conflict ko-cy 12 1 3 ./result/ft_conflict/dataset/train_ko-cy.jsonl
bash ./src/utils/single_ft_script.sh ft_conflict ko-sw 12 1 3 ./result/ft_conflict/dataset/train_ko-sw.jsonl
bash ./src/utils/single_ft_script.sh ft_conflict ko-zu 12 1 3 ./result/ft_conflict/dataset/train_ko-zu.jsonl
bash ./src/utils/single_ft_script.sh ft_conflict ko-tk 12 1 3 ./result/ft_conflict/dataset/train_ko-tk.jsonl
bash ./src/utils/single_ft_script.sh ft_conflict ko-gd 12 1 3 ./result/ft_conflict/dataset/train_ko-gd.jsonl
bash ./src/utils/single_ft_script.sh ft_conflict sv-ta 12 1 3 ./result/ft_conflict/dataset/train_sv-ta.jsonl
bash ./src/utils/single_ft_script.sh ft_conflict sv-mn 12 1 3 ./result/ft_conflict/dataset/train_sv-mn.jsonl
bash ./src/utils/single_ft_script.sh ft_conflict sv-cy 12 1 3 ./result/ft_conflict/dataset/train_sv-cy.jsonl
bash ./src/utils/single_ft_script.sh ft_conflict sv-sw 12 1 3 ./result/ft_conflict/dataset/train_sv-sw.jsonl
bash ./src/utils/single_ft_script.sh ft_conflict sv-zu 12 1 3 ./result/ft_conflict/dataset/train_sv-zu.jsonl
bash ./src/utils/single_ft_script.sh ft_conflict sv-tk 12 1 3 ./result/ft_conflict/dataset/train_sv-tk.jsonl
bash ./src/utils/single_ft_script.sh ft_conflict sv-gd 12 1 3 ./result/ft_conflict/dataset/train_sv-gd.jsonl
bash ./src/utils/single_ft_script.sh ft_conflict da-ta 12 1 3 ./result/ft_conflict/dataset/train_da-ta.jsonl
bash ./src/utils/single_ft_script.sh ft_conflict da-mn 12 1 3 ./result/ft_conflict/dataset/train_da-mn.jsonl
bash ./src/utils/single_ft_script.sh ft_conflict da-cy 12 1 3 ./result/ft_conflict/dataset/train_da-cy.jsonl
bash ./src/utils/single_ft_script.sh ft_conflict da-sw 12 1 3 ./result/ft_conflict/dataset/train_da-sw.jsonl
bash ./src/utils/single_ft_script.sh ft_conflict da-zu 12 1 3 ./result/ft_conflict/dataset/train_da-zu.jsonl
bash ./src/utils/single_ft_script.sh ft_conflict da-tk 12 1 3 ./result/ft_conflict/dataset/train_da-tk.jsonl
bash ./src/utils/single_ft_script.sh ft_conflict da-gd 12 1 3 ./result/ft_conflict/dataset/train_da-gd.jsonl